# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwrod',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
