# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171026_1041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('abc', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
