# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6807\u9898')),
                ('created', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
    ]
