# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '00010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
    ]
