# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='remark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
