# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0004_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
