# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0005_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='srcfile',
            field=models.FileField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
