# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0009_post_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sex1',
            field=models.NullBooleanField(),
        ),
    ]
