# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0010_post_sex1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='orderId',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
