# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0011_post_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
