# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0008_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
