# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileds', '0012_post_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
